-- 코드를 입력하세요
SELECT 
DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_DATE, 
PRODUCT_ID, 
NULL AS USER_ID, 
SALES_AMOUNT
from OFFLINE_SALE n 
where MONTH(n.SALES_DATE) = '3'
UNION ALL
SELECT
DATE_FORMAT(SALES_DATE,'%Y-%m-%d') as SALES_DATE, 
PRODUCT_ID, 
USER_ID, 
SALES_AMOUNT
FROM
ONLINE_SALE
WHERE MONTH(SALES_DATE) = '3'
order by SALES_DATE asc, PRODUCT_ID asc ,USER_ID asc