-- 코드를 작성해주세요

# select ROUTE,
#     CONCAT(ROUND(sum(D_BETWEEN_DIST),1),'km') as TOTAL_DISTANCE,
#     CONCAT(ROUND(avg(D_BETWEEN_DIST),2),'km') as AVERAGE_DISTANCE 
#     from SUBWAY_DISTANCE 
#     group by ROUTE 
#     order by TOTAL_DISTANCE DESC
    
    SELECT ROUTE, 
CONCAT(ROUND(SUM(D_BETWEEN_DIST), 1), 'km') TOTAL_DISTANCE, 
CONCAT(ROUND(AVG(D_BETWEEN_DIST), 2), 'km') AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 2) DESC;